apiVersion: v1
kind: Service
metadata:
  name: gpsd-user-mgmt
  namespace: gpsd
spec:
  selector:
    app: gpsd-user-mgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5500
      nodePort: 30055
  type: NodePort

